# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beff1166675316ef6e600f647404778eb40ffc4e1ab5056816e61b2da9f84dc9398ab7225e06b063111f9d9733fb11d34d40e4c327a600ad3bc44c9a51924362

test:
  secret_key_base: 65c4b2c81885ea5e05be0a2562aeba2fda383673f8e4d17b9e18f89030cc0a4175fef793cf415b90cef29afd27a5b5a92d208421217e9131e0d59d54783c4c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
